.release.json
Version number no longer depends on datetime
使用当前分支最新tag之后的commit数量当做版本号+r之后的值，不再依赖日期和时间
=> refactor: use commit count for the package version

.packit.yaml, rpm/dtkcore.spec
This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log: Initial packit setup
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
=> feat: Initial packit setup

src/log/RollingFileAppender.cpp
被分割的日志文件，名称包含毫秒却缺少秒。完善该信息有助于在大量日志文件中快速找到准确时间段的日志文件。
Log: 优化日志文件名称
=> style:Improve log file name

src/settings/dsettings.cpp, tests/tests.pro, tests/ut_qsettingsbackend.cpp
DSettingsBackend::doSetOption is executing when `DSettings` has
been destroyed, because `doSetOption` is connected in `QueuedConnection`
way, this would be ensure `backendWriteThread`'seventloop is exited
when `DSetting` destoryed.
we ensure `DSettings` is released before `SettingBackend`, so that
`SettingBackend`'s slot would not be executed when `DSetting` destoryed.
we also should ensure `SettinBackend` is thread safely, because os
`DSettings` has backendWriteThread to execute doSetOption, and getOption,
is execute in main thread.
remove link of libdtkcore in qmake, because we compile it's source code
in unit test.
Log:
=> fix: DSetting unit error and crash randomly

src/dconfig.cpp, tests/ut_dconfig.cpp, tests/ut_dconfigfile.cpp
Add invalid check for all DConfig's method(avoid null pointer dereference).
fallback to FileBackend when DBusBackend can't be created.
set correct environment value in unit test.
Log:
Influence: all application crash when dconfig is invalid but still
call other method expect isValid.
Change-Id: I7395f44518989cb14a09306fcfd4db380608a24e
=> fix: application crash when dconfig is invalid

src/filesystem/filesystem.pri
dde-config-daemon loads resouce from `$$PREFIX/share/dsg` when default
action, and `PREFIX`'s value is empty.
set default value for PREFIX from QT_INSTALL_PREFIX(/usr).
Log: 
Influence: 开发dtkcore，但没有指定PREFIX值，导致配置策略加载失败
Change-Id: I97573c283365aa581d5e93eb75d27259134f10af
=> fix: DConfig can't find resource

src/src.pro
`include.files+=` is behind `load(dtk_build)`, so those files don't
execute dtk_build function, it casues dtkcore_config.h don't include
`include.files` in `dtk_build` back.
Log: 
Change-Id: I06afe3df5c80145d7d9ff9da281571a9725366d5
=> chore: dtkcore_config.h miss include some Class

CMakeLists.txt, debian/rules, doc/CMakeLists.txt
追加基于 doxygen 的文档构建
说明：
1. 目前并不会打包文档包，也不会自动生成和发布文档。文档包会在后续 PR 中提供，在线文档的生成和发布会在以后的 CI 流程中进行
2. 为了各个项目统一，文档会固定生成在对应 build 目录内的 docs 子目录中
3. 默认只生成 QCH 文档，但对外暴露了其他格式的生成选项，以便通过 cmake 的缓存变量的形式控制实际行为，也可通过 `ccmake` 等工具调整对应的值
4. 生成 HTML 文档的参考命令：`cmake ../ -DDOXYGEN_GENERATE_HTML="YES" -DDOXYGEN_HTML_EXTRA_STYLESHEET="/path/to/extra-stylesheet.css" -DDOXYGEN_TAGFILES="qtcore.tags=http://qt-project.org/doc/qt-5/"`
5. 若要确保对 Qt 类型的正确生成，则需先拷贝 Qt 的 tags 文件（比如 `/usr/share/doc/qt/qtcore/qtcore.tags`）到 doxygen 的工作目录（此例为源码根目录），然后再进行文档的生成
=> chore: build doxygen documentation

src/src.pro
It should link to dl for some distrbutions. For example, openSUSE.
The compiling won't be success without this link.
log:
=> Fix: link to dl

src/filesystem/dfilewatcher.cpp
Correct a typo.
Log: Fix a typo in dfilewatcher.cpp
=> chore: fix a typo in dfilewatcher.cpp

doc/CMakeLists.txt
处理了两个问题：
1. 错误的宏预定义配置
2. 项目整体改 CMake 后，遗漏的 include 目录
此修改后，可重新使类如 DConfig 之类的文档正常生成内容，且位于正确的名称空间内。
=> fix: missing include folder while generating documentation

include/DtkCore/DCapDir, include/DtkCore/DCapFile, include/DtkCore/DCapManager, include/filesystem/dcapfile.h, include/filesystem/dcapmanager.h, src/filesystem/dcapfile.cpp, src/filesystem/dcapfsfileengine.cpp, src/filesystem/dcapmanager.cpp, src/filesystem/filesystem.cmake, src/filesystem/filesystem.pri, src/filesystem/private/dcapfsfileengine_p.h, src/filesystem/private/private.pri, tests/CMakeLists.txt, tests/ut_dcapfile.cpp
Use DCapManager class to unify privilege management on
whether to open files or not.
By registering a special file engine, the scope of action
after registration is global unless called the unregister
function manually.
By default, the application can still access some directories
and files with permissions after it is started, but when it
access files beyond the scope of these directories, it will
not get any information.
The default directory includes: Home path; Cache path; DSG path
XDG path etc.
Log:
Influence: null
Change-Id: I0fed6051addc56001b382fc34f73b046c0e4aca2
=> feat: add the permission management for files

src/dconfig.cpp, src/dconfigfile.cpp
Change Warning log to Debug.
Rename GlobalUID to InvalidUID avoiding to misunderstand.
cache saved only it's setValue has been called.
Log: 移除错误的输出警告，当cache被修改后才保存
Influence: 如果没有设置值，再不会生成缓存文件
Change-Id: I1f71513e91bef3412f593281e68fea44801fe07b
=> chore: Modify some nonstandard writing

CMakeLists.txt
修复错误的 `option()` 用法。
Review 的时候有一些细节要注意，可能也待讨论：
1. 原本用的 `DVERSION` 是故意的？如果希望外部通过 `-DVERSION` 参数来修改的话，变量名应该是 `VERSION` 才对。
2. 与版本号相关，看到定义了一个单独的 `BUILD_VERSION`，目的是什么？如果是第四位版本号的话，为什么不直接用 [`PROJECT_VERSION_TWEAK`](https://cmake.org/cmake/help/latest/variable/PROJECT_VERSION_TWEAK.html#variable:PROJECT_VERSION_TWEAK)？
当然目前看这个 CMakeLists.txt 还有一些别的问题，就不在这个 PR 里讨论了。
此 PR 讨论结束并合入后，其他 DTK 组件也需要进行相应的调整。
=> fix: wrong option() usage in CMakeLists.txt

misc/DtkConfig.cmake.in
Log： deepin 中，tool 会被分到和 dev 不同的 bin 包，因此 dev 提供的 config.cmake  不应该检查 DtkCore_TOOL_DIR 是否存在
=> fix: don't check DtkCore_TOOL_DIR cause split pkgs

CMakeLists.txt
Log: dtk 5 与 dtk 6 不保证兼容，使用 SameMajorVersion 更好
=> chore: use SameMajorVersion in version file

CMakeLists.txt, debian/rules, tools/qdbusxml2cpp/CMakeLists.txt
Log: Optimize compilation parameters
Ref: https://deepin-community.github.io/sig-dde-porting/posts/compile_flag
=> feat: Optimize compilation parameters

include/DtkCore/DError, include/DtkCore/DExpected, src/CMakeLists.txt, src/base/base.cmake
以及derror.h
Log: 添加dexpected.h的CMake安装规则
=> chore: add CMake rules for installing dexpected.h

src/CMakeLists.txt
the first time turn to cmake, the definition is missing
Log: return the missingdefinition
=> fix: missingdefinition

include/base/dexpected.h
1. 修复reinit函数因类型约束不完整导致的编译错误
2. 修复likely/unlikely宏中因为类型转换导致的编译错误
3. 给DUnexpected模板增加DError默认模板类型
Log: 修复reinit函数的不完整实例化
=> fix: fix reinit imcomplete instantiation

include/base/dexpected.h
不需要保留此变量,因为所有构造函数总会初始化value和error其中之一
Log:移除不必要的成员
=> improvement: remove unnecessary variant member

src/log/Logger.cpp
LoggerPrivate not init..
Log: 修复帮助手册在升级dtkcore后无法打开的问题
Bug: https://pms.uniontech.com/bug-view-172121.html
Change-Id: Ieee74154a33260043af264a176dabc672a17f559
=> fix: Logger constructor crash

include/log/win32/OutputDebugAppender.h
fix license in win32/OutputDebugAppender.h
=> chore: fix license

src/dsysinfo.cpp
分别按以下顺序取其值，取到就返回：
1. 首先匹配sw，hw-klv里的特殊字段；
2. 然后取model name字段；
3. 最后通过lscpu命令获取；
Log: 修改cpu信息获取接口
Task: https://pms.uniontech.com/task-view-218217.html
Influence: cpuModelName接口
Change-Id: I6ba1a66f1d898725ebcb9a59791f6d466149a3a3
=> chore: 完善cpu信息获取接口（cpuModelName）

include/log/RollingFileAppender.h, src/filesystem/dcapfile.cpp, src/log/RollingFileAppender.cpp
add missing imple of rollingfileappender
use Use QFile::symLinkTarget() instead of QFile::readLink()
Log: none
Change-Id: I7cf642fed010bcb73f1c3ebca0c2bfd3a6795dad
=> fix: missing implementation and obsolete Member

docs/global/dconfig.zh_CN.dox
dconfig的@brief注解与详细描述间添加空行
Log:
=> fix: fix dconfig docs

include/util/ddbusinterface.h
Delete an undefined overloader constructor of DDBusInterface.
Log: delete an constructor
Influence: DDBusInterface
=> fix: delete an undefined overloaded function

docs/settings/backend/gsettingsbackend.zh_CN.dox, src/settings/backend/gsettingsbackend.cpp
给gsettingsbackend添加文档注释 #181 
Log: add docs
=> docs: add docs for settings

tools/dci/CMakeLists.txt, tools/dci/main.cpp
1. add --tree args to view files in dci file
2. install dci cli tool in libdtkcore5-bin
3. fix invaild link when export dci file
```
./dci --tree ~/Desktop/ps.dci/android-device.dci
/
└── /256
├── normal.dark
│   ├── 2
│   │   └── 1.webp -> /256/normal.light/2/1.webp
│   └── 3
│       └── 1.webp -> /256/normal.light/3/1.webp
└── normal.light
├── 2
│   └── 1.webp
└── 3
└── 1.webp
```
=> chore dci tool and install dci cli tool

include/base/dexpected.h
由于在C++20中引入的Concept机制和SFINAE机制完全不一样,在C++20之前无法做到相同形式的约束效果,所以放宽约束条件
Log: 修复可平凡构造类型不能被构造的错误
=> fix: fix trivially copy/move constructiable type can't be constructed

src/dsysinfo.cpp
QStorageInfo::root().device()扫描的是/etc/mtab里的内容，但是有的根节点就只会显示/dev/root，这个会导致在控制中心显示磁盘容量的时候不能 显示，故现更改获取根挂载点的方式，在lsblk的方法上增加。
Log:
=> chore: Update dsysinfo.cpp

src/dsysinfo.cpp
from https://github.com/linuxdeepin/dtkcore/pull/40 QStorageInfo::root().device()扫描的是/etc/mtab里的内容，
但是有的根节点就只会显示/dev/root，这个会导致在控制中心
显示磁盘容量的时候不能显示，故现更改获取根挂载点的方式，
在lsblk的方法上增加。
Log:
Influence: systemDiskSize
Change-Id: I95a4955ae6d862df6c66b3d09f42b92285967ca9
=> chore: use mountpoint to find root device

src/dconfigfile.cpp
cleanPath for file path.
cacheChanged is reset when saved avoid to resaving.
Log: none
Change-Id: I5bf6c2165ad19a66ad7684d696bef97c3432f0fa
=> fix: Cleaning path about dconfigfile

archlinux/PKGBUILD, debian/rules, src/CMakeLists.txt, src/glob.cmake, tests/CMakeLists.txt
Add adjust for linux when compile.
Add `D_DSG_APP_DATA_FALLBACK` macro when packaging.
see the commit: 7b13e5c4b867fcbdcc50f5e409b0c8726496b7e5
Log: none
Change-Id: Ie047dbd2d8158ed5242dfb5bcc7fa4e02ee1d925
=> fix: Losing dconfig info when compiling and packaging

cmake/DtkDConfig/DtkDConfigConfig.cmake
Add quotation mark for macro.
Log: none
Change-Id: Iaf26210a81e7c2e167e30b976c5e0a1ec26708b9
=> fix: Lossing quotation mark for DSG_DATA_DIR macro

src/CMakeLists.txt
Define macro to be used in cpp.
Log: none
Change-Id: I40f743e74b5a5c5eb8e94e4ba099747d3d88523d
=> fix: missing BUILD_WITH_SYSTEMD macro

docs/filesystem/index.zh_CN.md, docs/global/index.zh_CN.md, docs/util/index.zh_CN.md
qhelpgenerator run failure due to wrong markdown title tree. Change index title level to fix.
Log: fix qch generate error
=> fix: qch generate error

docs/global/dconfig.zh_CN.dox, docs/global/dconfigfile.zh_CN.dox, include/global/dconfig.h, include/global/dconfigfile.h, src/dconfig.cpp, src/dconfigfile.cpp, tests/ut_dconfig.cpp, tests/ut_dconfigfile.cpp
All application use same configuration by empty appid.
Loading cache file can fallback to noappid's directory when not
using appid or not find cache file.
one application writes configuration.
```c++
auto config = DConfig::createGeneric(FileName);
config->setValue("common-configuration", true);
```
other applications read configration can give appid or not to
get the configuration.
Set empty string for DBus caller when using `acquireManager`.
Log: 配置策略支持空appid，缓存精准匹配到meta是否使用appid
Change-Id: I78b331f9c455617d5dfea6df087b1f4828390974
=> feat: Add empty appid support for DConfig

debian/control
dconfig prf and cmake modules were move to dtkcore dtkcommon depends >= 5.6.4
Log: fix install conflict
=> chore: specify dtkcommon version

src/filesystem/dcapmanager.cpp
Log: 暂时修复由于qt使用relocatable特性编译时QDebug析构时产生的死循环
=> fix: Temporarily fix the dead loop generated by QDebug destructor when compiling with the relocatable feature of qt

include/util/dvtablehook.h, src/util/dvtablehook.cpp, tests/testso/testso.cpp, tests/testso/testso.h, tests/ut_dvtablehook.cpp
1. 修复了因不完整拷贝引起的rtti信息丢失的问题
2. 对于虚表结尾判断增加了新的限制条件
3. 增加了调整虚表指针的方法, 后续可以考虑取消对于函数指针和对象指针类型一致的限制
Log: 修复不完整的虚表拷贝
=> fix: Fix incomplete copy of Vtable

include/filesystem/dcapmanager.h, src/filesystem/dcapmanager.cpp, tests/ut_dcapfile.cpp
由于在开启Relocatable的Qt上,
注册DCapFileEngine会影响到Qt内部代码产生错误的结果,
并且并没有很好的办法判断某个文件是否应该由DCapFileEngine作为后端,
所以移除
Log: 移除DCapFSFileEngine
=> fix!: remove DCapFSFileEngine

include/log/Logger.h, src/log/Logger.cpp
相关issue：https://github.com/linuxdeepin/dtkcore/issues/292
Log: 当没有注册对应的category时输出log信息到所有的appender
=> feat: append to all appenders when category is not registered

docs/global/dconfigfile.zh_CN.dox, include/global/dconfigfile.h, src/dconfigfile.cpp, tests/ut_dconfigfile.cpp
Add setCachePrefix function to support that cache can be relocated
by caller, It's default value doesn't changed, and we can refer to
`配置文件规范` in https://github.com/linuxdeepin/deepin-specifications.
Permissions is left to the caller.
For DConfig's FileBackend, we use it's default value.
Issue: https://github.com/linuxdeepin/dtkcore/issues/271
=> feat: Support cache to be relocated for DConfigFile

src/dsgapplication.cpp
We shouldn't store appId fallback to applicationName.
=> fix: AppId fetch error when fallback to applicationName

include/util/dutil.h, src/dsecurestring.cpp
=> fix: incorrect DSecureString destructor

src/dsysinfo.cpp
Log: bring back cache for caculate memoryInstalled
https://github.com/linuxdeepin/dtkcore/commit/63d6f5c4b39cae172e7fff1a3a92dc4da4f739a0
原来这个计算是有缓存的，看起来是什么时候丢了
=> chore: back cache of caculate memoryInstalled

include/util/dvtablehook.h, src/util/dvtablehook.cpp
The functions are used in template, and they aren't inline,
so we can't delete them in this version, but we can remove their implementation.
It caused in fb4845350a4a957257118a1475d4078f75578c01
=> chore: Revert deleted function for DVtableHook

src/dconfigfile.cpp, tests/data.qrc, tests/data/dconf-example.override.noexistitem.json, tests/ut_dconfigfile.cpp
We shouldn't add the item when override file has no existed
item in meta items.
=> feat: DConfig add check for no existed item when override

CMakeLists.txt, tests/CMakeLists.txt
* BUILD_VERSION should be a string, not a boolean option;
* Should use CMAKE_INSTALL_PREFIX as DSG_PREFIX_PATH in test, CMAKE_PREFIX_PATH might be a list. And there's difference between two variables;
* Trim some trailing spaces.
Log: fix wrong use of option and wrong macro
=> fix(cmake): wrong use of option and wrong macro

include/util/ddbussender.h, src/util/ddbussender.cpp
When creating QAbstractInterface, Qt will try to invoke instrospection into the DBus path, this is sometimes costing when instrospection is not ready for that path. Change the implementation of DDBusSender. Don't use QDBusInterface. Instead, create a QDBusMessage and invoke it directly. This is sensible because DDBusSender is just a wrapper like QDBusInterface, it shouldn't rely on QDBusInterface.
Issue: https://github.com/linuxdeepin/developer-center/issues/4415
Log: fix calling delay in DDBusSender
=> fix: calling delay in DDBusSender

src/dconfigfile.cpp
Avoid to access unprivileged directory by DConfig's subpath.
Issue: https://github.com/linuxdeepin/dde-app-services/issues/54
=> feat: DConfig add check for subpath

src/dconfigfile.cpp, tests/ut_dconfigfile.cpp
It's correctly even if subpath is not exist, so we can't use
`QDir::canonicalPath` to adjust subpath.
Add ut.
=> fix: DConfig's `subpathIsValid` produces error

docs/util/dtextencoding.zh_CN.dox, include/util/dtextencoding.h, src/util/dtextencoding.cpp, tests/ut_dtextencoding.cpp
1. Fix DTextEncoding muti-byte encoding calculation error.
2. Replace QTextCodec with QStringConverter in Qt6 env.
3. Add convertedBytes param in the convertTextEncodinig() interface.
Log: Fix DTextEncoding ut failed in Qt6.
=> fix: DTextEncoding ut failed in Qt6.

cmake/DtkTools/DtkToolsConfig.cmake.in, tools/qdbusxml2cpp/CMakeLists.txt
Now qdbusxml2cpp-fix is not in PATH, just export it as a target so others can use it.
Log: fix qdbusxml2cpp-fix not in path
=> fix: qdbusxml2cpp-fix not in path

src/util/ddbusinterface.cpp, src/util/ddbusinterface_p.h
有的服务属性改变时不会发送 ProperiesChanged 导致属性变化后再次
获取属性时还是旧的 value ，因为缓存不会更新
=> chore: remove ddbusinterface property cache

debian/control
libdtkcore5 does not depend libdtkcommon
=> chore: remove libdtkcommon depends

tests/CMakeLists.txt, tests/fakedbus/fakedbusservice.h, tests/test-recoverage.sh, tests/ut_ddbussender.cpp
- set -e : exit if command has a non-zero exit status
- fix test target name ut-DtkCore
- tweek FakeDBusService. add metho and read/write propery
- test DDbusSender. call dbus method and get/set dbus property
=> add ut for DDbusSender

archlinux/PKGBUILD
Should extract correct tag version from pkgver and then pass to cmake.
* extract tag version and pass to cmake
* format PKGBUILD for fewer changes in the future
* provide a more sensible default pkgver
Log: fix incorrect version passed to cmake in archlinux build
=> fix: incorrect version passed to cmake in build

src/log/rollingfilesink_p.h
fmt_lib introduced after v1.9.2 in spdlog.
=> fix: Compiling failed in lower libspdlog-dev

.github/workflows/call-synchronize-to-dtk6.yml
Synchronize-to-dtk6 parameter passing has changed. Synchronize the
new usage.
Log: synchronize new form of parameter passing for synchronize-to-dtk6
Related-to: https://github.com/linuxdeepin/dtk/pull/129
=> fix: missing parameter passing for synchronization

src/log/rollingfilesink_p.h
spdlog::memory_but_t and spdlog::wmemory_but_t are introduced after 1.4.0.
UOS 1060 ships with libspdlog-dev 1.3.1, this fix solved the compiling failed in UOS.
=> fix: Compiling failed in libspdlog-dev before 1.4.0

src/util/dpinyin.cpp, tools/ch2py/main.cpp
- remove duplicate results when permuting and combining Pinyin
- limit the number of results to avoid of OOM
- ch2py print elapsed time
Issue: https://github.com/linuxdeepin/dtk/issues/109
=> chore: dpinyin tweak

tools/qdbusxml2cpp/qdbusxml2cpp.cpp
We get typeName using `QMetaType::name` in qt6.
=> fix: Type error for qdbusxml2cpp

docs/global/dconfigfile.zh_CN.dox, include/global/dconfigfile.h, src/dconfigfile.cpp, tests/data/dconf-example.meta.json, tests/ut_dconfigfile.cpp
add flag userPublic to Meta file for managing permission among users.
Issue: https://github.com/linuxdeepin/developer-center/issues/5928
=> chore: add flag userPublic

docs/filesystem/dstandardpaths.zh_CN.dox, include/filesystem/dstandardpaths.h, src/filesystem/dstandardpaths.cpp
this folder is used to storage history and logs
Log:
ref: https://gitlab.freedesktop.org/xdg/xdg-specs/-/commit/4f2884e16db35f2962d9b64312917c81be5cb54b
=> feat(dstandardpaths): add XDG_STATE_HOME

src/util/dpinyin.cpp
set is unordered, results are inconsistent
=> chore: keep order when deduplication

src/dsgapplication.cpp
We don't block application when AM is unavailable.
=> fix: app blocked when AM is unavailable

include/util/dutil.h
=> chore: remove decltype(auto) for dutil

tools/dci/main.cpp
```
dci --export ./ ./xxx.dci
```
应该是 ./1.webp ->  ../../normal.light/3/1.webp
=> chore: fix relative path invalid link

cmake/DtkTools/DtkDBusMacros.cmake, tools/qdbusxml2cpp/qdbusxml2cpp.cpp
Log:
Issue: https://github.com/linuxdeepin/dtk/issues/147
=> feat: allow skip including headers of annootations

docs/global/dconfig.zh_CN.dox, include/global/dconfig.h, src/dconfig.cpp
It's useful for generic config to clearly specify application id.
=> feat: support to set appId for DConfig

src/dconfigfile.cpp, tests/ut_dconfigfile.cpp
user can open non-root controlled files when `name` is relative path.
Issue: https://bugzilla.suse.com/show_bug.cgi?id=1211374
=> fix: DConfig add check for name

src/dconfig.cpp
Blocking caller until it's finished, otherwise
it maybe lose value when application is quit early.
=> fix: lossing value when save DConfig

src/log/ConsoleAppender.cpp
Support spdlog 1.14.0
Log: spdlog 1.14.0 added string view overloads for logger accessor. We should include more headers for this change in dtkcore.
=> fix: fix undefined reference errors on spdlog 1.14.0

tools/qdbusxml2cpp/qdbusxml2cpp.cpp
=> chore: remove warning for dbusxml2cpp in qt6

src/dconfigfile.cpp, tests/ut_dconfigfile.cpp
user can open non-root controlled files when `appId` is relative path.
Issue: https://bugzilla.suse.com/show_bug.cgi?id=1211374
=> fix: DConfig add check for AppId

src/dconfigfile.cpp, tests/ut_dconfigfile.cpp
Empty is used in dde-dconfig-daemon, and it is valid.
=> fix: DConfigFile is invalid when AppId is empty

debian/rules, include/global/dsysinfo.h, include/log/LogManager.h, src/dsysinfo.cpp, src/log/AbstractStringAppender.cpp, src/log/ConsoleAppender.cpp, src/log/LogManager.cpp
-  允许基于dtk开发的应用动态控制其日志输出等级 
-  lshw查询内存大小时返回多元素数组,修正解析过程
- 从文件中读取deepinType和productType值时因为权限问题会失败
- 增加registerLoggingRulesWatcher接口
- 修复计算 build 版本号错误的问题 
- 修复日志格式时间戳显示异常问题
https://github.com/linuxdeepin/dtkcommon/pull/70
=> Loggingrules dconfig support (cherry-pick from gerrit)

src/dsgapplication.cpp
Add fallback, using fileName of /proc/self/exe as AppId.
Remove assert for empty appId.
=> fix: crashed when access DSGApplication::id early

src/dci/private/ddcifileengine.cpp, src/dci/private/ddcifileengine_p.h
QAbstractFileEngine::FileTime ==> QFile::FileTime
=> fix(build): build faild on Qt6.7

src/log/LogManager.cpp
=> chore: add nullptr check

include/util/dutil.h
一些项目使用了 -fno-operator-names，会导致编译失败
=> chore: use '&&' and '||' instead of 'and' and 'or'

src/CMakeLists.txt
These two libraries are used to detect text encoding, 
but they are actually loaded dynamiclly.
Not need to link libraries.
=> fix: remove unnecessary link libraries

include/util/dutil.h
=> fix(util): error appid from `getAppIdFromAbsolutePath`

src/dci/private/ddcifileengine.cpp, src/dci/private/ddcifileengine_p.h, src/filesystem/dcapfsfileengine.cpp, src/filesystem/private/dcapfsfileengine_p.h
=> feat: support Qt 6.8

debian/rules
=> fix(build): debian/rule use tab instead of space

src/util/dvtablehook.cpp
Destruct function should be called by 'autoCleanVtable' instead of
'callOriginalFun'.
'glostVtable' should be delete before calling origin destruct,
because 'resetVtable' maybe called when destructing origin destruct.
pms: BUG-368399
=> fix: hasVtable is incorrect when destructing

src/dsgapplication.cpp
pidfd must be closed by caller according QDBusUnixFileDescriptor.
pms: BUG-293049
=> fix: pidfd leak

src/dconfigfile.cpp, tests/data/dconf-example.meta.json, tests/ut_dconfigfile.cpp
MetaType of 1.0 is qlonglong instead of double in json file.
We don't convert if source value is double.
=> fix: double value is converted to int for DConfig

.reuse/dep5
This is a generate file, so copyright is none.
=> fix: add copyright for dconfig_org_deepin_dtk_preference.hpp

CHANGELOG.md, debian/changelog, include/util/dvtablehook.h, tools/dconfig2cpp/main.cpp
Updated the dvtablehook.h file to adjust the typedef for Fun2ReturnType based on changes in Qt 6.9 interfaces. Additionally, the main.cpp file now casts the unicode value to short to prevent type issues. These changes are necessary to ensure compatibility with the latest Qt framework and to resolve the build issues that arise from interface modifications.
修复: 解决在Qt 6.9上的编译失败
更新了dvtablehook.h文件，以根据Qt 6.9接口的变化调整Fun2ReturnType的 typedef。此外，main.cpp文件现在将unicode值转换为short，以防止类型问题。
这些更改对于确保与最新Qt框架兼容以及解决接口修改引起的构建问题是必要的。
=> fix: resolve compilation failure on Qt 6.9

src/dsysinfo.cpp
Added case 9 to return UosMilitary/UosMilitaryS in uosEditionType
function
The change was necessary because the system needs to recognize edition
type 9 as a valid military edition variant
This ensures proper handling of all supported UOS edition types in the
system
fix: 添加缺失的 UosMilitary 版本类型处理
在 uosEditionType 函数中添加了 case 9 返回 UosMilitary/UosMilitaryS 的
处理
此变更是必要的，因为系统需要将类型9识别为有效的军事版本变体
这确保了系统中对所有支持的 UOS 版本类型的正确处理
pms: BUG-316837
=> fix: add missing UosMilitary edition type cases

src/log/LogManager.cpp
1. Modified condition to check for both DTK_DISABLED_LOGGING_RULES and
QT_LOGGING_RULES environment variables
2. This change prevents logging rules from being initialized when either
variable is set
3. Ensures better compatibility with Qt's standard logging configuration
system
4. Maintains backward compatibility while adding support for standard Qt
logging control
fix: 改进日志规则环境变量处理
1. 修改条件以同时检查 DTK_DISABLED_LOGGING_RULES 和 QT_LOGGING_RULES 环
境变量
2. 当任一变量设置时，阻止日志规则初始化
3. 确保与 Qt 标准日志配置系统更好的兼容性
4. 在添加对标准 Qt 日志控制支持的同时保持向后兼容
=> fix: improve logging rules environment variable handling

src/dconfigfile.cpp
1. Added missing copy of cachePrefix member when copying DConfigFile
objects
2. The cachePrefix was being lost during copy operations which could
lead to incorrect cache behavior
3. This ensures complete and proper copying of all cache-related data
fix: 在 DConfigFile 拷贝构造函数中复制 cachePrefix
1. 添加了对 cachePrefix 成员的拷贝操作，在复制 DConfigFile 对象时该成员
之前被遗漏
2. 之前拷贝操作会丢失 cachePrefix，可能导致缓存行为异常
3. 此修改确保所有缓存相关数据都能被完整正确地拷贝
=> fix: copy cachePrefix in DConfigFile copy constructor

.github/workflows/auto-release.yml, rpm/dtkcore.spec
1. Changed version parameter from required to optional in auto-
release.yml
2. Fixed spec file formatting for Version and Release fields
3. Added %{?dist} macro to Release field for better RPM compatibility
The changes make the release workflow more flexible by allowing version-
less releases when needed. The spec file formatting improvements ensure
consistency with RPM packaging standards, while the %{?dist} macro helps
with proper package distribution tagging.
fix: 在发布工作流中使版本参数可选
1. 在 auto-release.yml 中将版本参数从必填改为可选
2. 修复了 spec 文件中 Version 和 Release 字段的格式
3. 在 Release 字段中添加了 %{?dist} 宏以提升 RPM 兼容性
这些改动使得发布工作流在需要时可以更灵活地进行无版本发布。spec 文件的格
式改进确保了与 RPM 打包标准的一致性，而 %{?dist} 宏有助于正确的软件包分
发标记。
=> fix: make version parameter optional in release workflow

src/dsgapplication.cpp
1. Added custom deleters for D-Bus resources (DBusError, DBusConnection,
DBusMessage)
2. Replaced manual resource cleanup with std::unique_ptr RAII wrappers
3. Simplified error handling by removing repetitive cleanup code
4. Improved memory safety by ensuring resources are always released
5. Added detailed documentation for getId() function explaining the
libdbus-1 usage
The changes ensure proper resource management even in error cases and
make the code more maintainable by eliminating manual cleanup. This is
particularly important for D-Bus operations that may fail at multiple
points. The RAII approach prevents resource leaks and makes the code
more robust.
refactor: 使用 RAII 改进 D-Bus 资源管理
1. 为 D-Bus 资源(DBusError, DBusConnection, DBusMessage)添加自定义删除器
2. 使用 std::unique_ptr RAII 包装器替代手动资源清理 …
=> refactor: improve D-Bus resource management with RAII

tools/qdbusxml2cpp/qdbusxml2cpp.cpp
Changed QSet to QStringList for annotations collection to ensure
deterministic output order
Added removeDuplicates() call to maintain uniqueness while preserving
order
This fixes non-reproducible builds caused by QSet's unpredictable
iteration order
Log: Fixed DBUS code generation reproducibility issue
Influence:
1. Verify DBUS interface code generation produces identical output for
same inputs
2. Test with multiple interface definitions containing annotations
3. Check build reproducibility across different systems
fix: 修复DBUS代码生成不可重复的问题
将注解集合从QSet改为QStringList以确保输出顺序确定性
添加removeDuplicates()调用在保持顺序的同时确保唯一性
修复了由于QSet迭代顺序不可预测导致的构建不可重复问题
Log: 修复了DBUS代码生成不可重复的问题
Influence:
1. 验证相同输入下DBUS接口代码生成是否产生相同输出
2. 测试包含多个注解的接口定义
3. 检查不同系统间的构建可重复性
=> fix: resolve non-reproducible DBUS code generation issue

include/global/dsysinfo.h, src/dsysinfo.cpp
增加系统类型 服务器教育版 服务器国防版 枚举
Log: 增加服务器教育版和国防版
Task: https://pms.uniontech.com/task-view-381681.html
Influence: 系统类型
Change-Id: I2806d86ff42d31199fc7a144bf9e8b0fc69c5fcd
=> feat: 增加服务器教育版和国防版

src/filesystem/dtrashmanager_linux.cpp
Changed rmdir to rename when handling directory operations in trash manager
The original code used rmdir to remove directories which could fail if directory is not empty
Using rename operation instead allows moving directories to trash location while preserving contents
This fixes potential data loss when trashing non-empty directories
fix: 将目录操作中的 rmdir 替换为 rename
在回收站管理器中处理目录操作时将 rmdir 改为 rename
原始代码使用 rmdir 删除目录，如果目录不为空则会失败
使用 rename 操作可以将目录移动到回收站位置同时保留内容
这修复了清空非空目录时可能出现的数据丢失问题
=> fix: replace rmdir with rename for directory operations
