linuxdeepin/dtkcore

src/dtk_translation.prf
=> fix: use "23417ROOT_DIR" replace "23417mod_inst_pfx/.."

src/dconfig.cpp, tests/data/dconf-example.meta.json, tests/ut_dconfigfile.cpp
using recursion to parse QDBusArgument.
Log:
=> fix: dconfig can't support embed complex data type

src/dconfig.cpp, src/dconfigfile.cpp
加载meta和override时，检测配置项是否有value字段
Log: 加载配置文件时，检测配置项是否有value字段
Influence: 配置策略
Change-Id: I9fe2f54fa76870139a6929dc46ce610de465abc8
=> feat: 加载dconfigfile时，添加value字段的检测

debian/changelog, src/DSGApplication, src/dci/DDciFile, src/dci/dci.pri, src/dci/ddcifile.cpp, src/dci/ddcifile.h, src/dci/private/ddcifileengine.cpp, src/dci/private/ddcifileengine_p.h, src/dconfig.cpp, src/dsgapplication.cpp, src/dsgapplication.h, src/filesystem/dfilesystemwatcher_linux.cpp, src/src.pro, tests/tests.pro, tests/ut_dconfig.cpp, tests/ut_ddci.cpp, tools/dci/dci.pro, tools/dci/main.cpp, tools/tools.pro
=> Merge develop/snipe to master

src/dsysinfo.cpp, src/dsysinfo.h
Signed-off-by: Han Gao <gaohan@deepin.org>
=> feat: add Gentoo for DSysInfo

src/dsysinfo.cpp, src/dsysinfo.h
=> feat: add NixOS for DSysInfo

README.md
=> fix: remove not supported syntax for README

.reuse/dep5, include/log/AbstractAppender.h, include/log/AbstractStringAppender.h, include/log/ConsoleAppender.h, include/log/CuteLogger_global.h, include/log/FileAppender.h, include/log/LogManager.h, include/log/Logger.h, include/log/RollingFileAppender.h, include/log/win32/OutputDebugAppender.h
=> chore: update REUSE license header

include/DtkCore/DDBusInterface, include/util/ddbusinterface.h, src/util/ddbusinterface.cpp, src/util/ddbusinterface_p.h, src/util/util.cmake
增加ddbusinterface2并且修改相关CMake文件
Log:增加ddbusinterface类
=> feat: add ddbusinterface

include/util/ddbusinterface.h, src/util/ddbusinterface.cpp, src/util/ddbusinterface_p.h
1. 去除编译警告，用 static 修饰变量
2. 空指针检测
Log: none
Change-Id: Ibf8b72a01f4450f0fdac54a2f6f7040535dd75ee
=> chore: 微调 ddbusinterface 类

include/util/ddbusinterface.h, src/util/ddbusinterface.cpp, src/util/ddbusinterface_p.h
can not emit property changed signal
Log:
=> fix(DDBusInterface): can not emit property changed signal

include/base/derror.h, include/base/dexpected.h
Dexpected作为错误处理模板类,Dunexpected作为辅助类
Log:加入Dexpected类
=> feat: add Dexpected class

include/base/derror.h, include/base/dexpected.h
Derror和Dunexpected同理
Log: Dexpected改名为DExpected
=> chore: change Dexpected to DExpected

README.md, README.zh_CN.md
README and licence under log folders
Log: fix licence
=> fix(licence): licence

include/global/dsysinfo.h, src/dsysinfo.cpp
bootTime; shutdownTime; uptime; arch
Log:
Change-Id: I460a517a6bdb6a980ebf8a6956c1dc8041274985
=> feat: add sysinfo interface

include/base/dexpected.h
=> feat: add default template parameter to type E

include/base/dexpected.h
=> refactor: correct function name has_value to hasValue

include/base/dexpected.h
=> fix: fix DExpected logic error

LICENSES/LGPL-2.1-or-later.txt, include/DtkCore/DDBusExtended, include/DtkCore/DDBusExtendedAbstractInterface, include/util/ddbusextended.h, include/util/ddbusextendedabstractinterface.h, src/util/ddbusextendedabstractinterface.cpp, src/util/ddbusextendedpendingcallwatcher.cpp, src/util/ddbusextendedpendingcallwatcher_p.h, src/util/util.cmake, tools/qdbusxml2cpp/qdbusxml2cpp.cpp
通过此类可以很方便得实现异步dbus通信
Log: add ddbusextendedabstractinterface
Change-Id: Ida45d0d22d065af3d86c7ad062419183572291dc
=> feat: add ddbusextendedabstractinterface

include/global/dsysinfo.h, src/dsysinfo.cpp
fix sw_64 build failed
Log: none
Change-Id: I0f0b997eeab1452155b0c4d0da11454e1df1de4e
=> fix: missing sw_64 architecture

docs/dsysinfo.zh_CN.dox, include/global/dsysinfo.h, src/dsysinfo.cpp
更新doxygen文档
TODO: 清理已经添加文档代码中中文注释
Log:
=> docs: update doxygen docs

docs/CMakeLists.txt, docs/log/dlogmanager.zh_CN.dox, src/log/LogManager.cpp
=> docs: add docs for DLogManager

src/dsysinfo.cpp
分别按以下顺序取其值，取到就返回：
1. 首先匹配sw，hw-klv里的特殊字段；
2. 然后取model name字段；
3. 最后通过lscpu命令获取；
Log: 修改cpu信息获取接口
Task: https://pms.uniontech.com/task-view-218217.html
Influence: cpuModelName接口
Change-Id: I6e8fe1ecc6c7fd4ce47eeb23ed521fd682b25ba1
=> chore: 完善cpu信息获取接口（cpuModelName）

docs/log/Logger.zh_CN.dox, include/log/Logger.h, src/log/Logger.cpp
=> docs: update Logger documents

docs/log/ConsoleAppender.zh_CN.dox, docs/log/FileAppender.zh_CN.dox, docs/log/RollingFileAppender.zh_CN.dox, docs/log/dlogmanager.zh_CN.dox, include/log/RollingFileAppender.h, src/log/ConsoleAppender.cpp, src/log/FileAppender.cpp, src/log/Logger.cpp, src/log/RollingFileAppender.cpp
=> docs: update dlog documents

.gitignore, docs/filesystem/dbasefilewatcher.zh_CN.dox, docs/filesystem/index.zh_CN.md, src/filesystem/dbasefilewatcher.cpp
=> docs: update filesystem documents

docs/util/dabstractunitformatter.zh_CN.dox, docs/util/index.zh_CN.md, src/util/dabstractunitformatter.cpp
Update docs for dabstractunitformatter.h.
Log: update docs
=> docs: update docs for util

docs/global/dconfig.zh_CN.dox, src/dconfig.cpp
=> docs: add dconfig docs

docs/dci/ddcifile.zh_CN.dox
=> fix: fix ddcifile docs

docs/filesystem/dcapfile.zh_CN.dox
更新文件模块文档
Log: 更新文档
Task: https://pms.uniontech.com/task-view-216407.html
=> docs: update dcapfile document

docs/settings/dsettings.zh_CN.dox, src/settings/dsettings.cpp
给dsettings添加文档注释
Log: add docs
Task: https://github.com/deepin-community/coding-quarter/issues/26
=> docs: add docs for settings

.github/ISSUE_TEMPLATE/document.md
=> chore: add ISSUE_TEMPLATE

README.md, README.zh_CN.md
=> docs: update README.md

README.md, README.zh_CN.md
=> fix: fix README.md

docs/util/ddbussender.zh_CN.dox
Add docs for DDBusSender, DDBusData, DDBusCaller, DDBusProperty.
Log: add docs for ddbussender.h
=> docs: add docs for ddbussender.h

docs/util/ddisksizeformatter.zh_CN.dox, docs/util/dtimeunitformatter.zh_CN.dox, src/util/ddisksizeformatter.cpp, src/util/dtimeunitformatter.cpp
Add docs for DDiskSizeFormatter and DTimeUnitFormatter.
Log: add docs for formatters
=> docs: add docs for formatters

docs/dci/ddcifile.zh_CN.dox, docs/filesystem/dbasefilewatcher.zh_CN.dox, docs/filesystem/dcapfile.zh_CN.dox, docs/filesystem/index.zh_CN.md, docs/global/dconfig.zh_CN.dox, docs/global/dsysinfo.zh_CN.dox, docs/global/index.zh_CN.md, docs/log/AbstractAppender.zh_CN.dox, docs/log/AbstractStringAppender.zh_CN.dox, docs/log/ConsoleAppender.zh_CN.dox, docs/log/Logger.zh_CN.dox, docs/log/RollingFileAppender.zh_CN.dox, docs/log/dlogmanager.zh_CN.dox, docs/log/index.zh_CN.md, docs/settings/dsettings.zh_CN.dox, docs/settings/dsettingsgroup.zh_CN.dox, docs/settings/index.zh_CN.md, docs/util/dabstractunitformatter.zh_CN.dox, docs/util/ddbusextentedabstractinterface.zh_CN.dox, docs/util/index.zh_CN.md, include/global/dsysinfo.h
更新文档,符合规范
https://github.com/linuxdeepin/dtkcore/issues/175
Log:
Task: https://pms.uniontech.com/task-view-216407.html
=> docs: update documents

include/util/dasync.h, tests/ut_dasync.cpp
Label DAsync as deprecated, delete all unit tests for it.
Log: label DAsync as deprecated
=> chore: label DAsync as deprecated

docs/global/dconfigfile.zh_CN.dox, src/dconfigfile.cpp
给dconfigfile添加文档注释 #196 
Log: add docs
=> docs: add docs for dconfigfile

docs/global/ddesktopentry.zh_CN.dox, include/global/ddesktopentry.h, src/ddesktopentry.cpp
给ddesktopentry添加文档注释 #197 
Log: add docs
=> docs: add docs for ddesktopentry

src/dsysinfo.cpp
Reverts linuxdeepin/dtkcore#203
=> Revert "chore: Update dsysinfo.cpp"

docs/global/dsysinfo.zh_CN.dox
给dsysinfo添加例子 #213 
Log: add example
=> docs: add example for dsysinfo

include/global/dsysinfo.h
=> chore: Update dsysinfo.h

docs/global/dsysinfo.zh_CN.dox, src/dsysinfo.cpp, tools/deepin-os-release/main.cpp
=> feat: optimization logic for other distribution

misc/DtkConfig.cmake.in, src/CMakeLists.txt
Remove pkg_check_modules for gsettings-qt
Log: remove dependency search
=> chore: remove dependency search

src/CMakeLists.txt
Change policy from PUBLIC to PRIVATE.
Log: modify include directories policy
=> chore: modify include directories policy

src/dtkcore_global.cpp
不需要此检查了
Log: 移除doubleLoadCheck
=> fix: remove doubleLoadCheck

archlinux/PKGBUILD
Modify PKGBUILD command to use relative path.
Log: modify PKGBUILD command
=> chore: modify PKGBUILD command

include/base/dexpected.h, include/util/ddbusinterface.h
=> docs: add some info about DExpected and DDBusInterface

tools/qdbusxml2cpp/qdbusxml2cpp.cpp
add DCORE_USE_NAMESPACE
Log: none
Change-Id: Ib9003d4f162732a1c17b4c7588f614b1c4d5580a
=> fix(build): dtkcore namespace not using

.reuse/dep5, CMakeLists.txt, cmake/DtkDConfig/DtkDConfigConfig.cmake, debian/changelog, misc/DtkCoreConfig.cmake.in, misc/dtk_install_dconfig.prf
Add DtkDConfigConfig.cmake file. Now find_package(DtkCore) can also find DConfig support.
Log: add DtkDConfig package
=> chore: add DtkDConfig package

docs/CMakeLists.txt
在打开build theme编译选项时会自动下载主题
Log:
=> docs: add doxygen theme

docs/filesystem/dbasefilewatcher.zh_CN.dox, docs/filesystem/dfilesystemwatcher.zh_CN.dox, docs/filesystem/dfilewarcher.zh_CN.dox, docs/filesystem/dfilewatchermanager.zh_CN.dox, src/filesystem/dfilewatcher.cpp, src/filesystem/dfilewatchermanager.cpp
=> docs: update docs

docs/filesystem/dfilesystemwatcher.zh_CN.dox, src/filesystem/dfilesystemwatcher_dummy.cpp
更新dfilesystemwatcher的文档 #237 
Log: update docs
=> docs: update dfilesystemwatcher docs

docs/filesystem/dfilewatchermanager.zh_CN.dox, examples/CMakeLists.txt, examples/filewatcher-example/CMakeLists.txt, examples/filewatcher-example/main.cpp, include/filesystem/dfilewatchermanager.h, src/filesystem/dfilewatchermanager.cpp, tests/ut_dfilewatchermanager.cpp
添加列出当前监控的文件列表的接口
添加删除全部监控的接口
Log:
=> feat: update file watcher manager

docs/filesystem/dfilewatchermanager.zh_CN.dox
=> docs: update dfilewatchermanager.zh_CN.dox

docs/filesystem/dtrashmanager.zh_CN.dox
=> docs: add dtrashmanager.zh_CN.dox

tests/CMakeLists.txt, tests/main.cpp, tests/testso/CMakeLists.txt, tests/testso/testso.cpp, tests/testso/testso.h, tests/ut_dvtablehook.cpp
Log: 修复DVtableHook和DConfig的单元测试
=> test: fix DVtableHook and DConfig's unit testing

docs/log/AbstractAppender.zh_CN.dox, docs/log/AbstractStringAppender.zh_CN.dox, docs/log/ConsoleAppender.zh_CN.dox, docs/log/FileAppender.zh_CN.dox, docs/log/Logger.zh_CN.dox, docs/log/RollingFileAppender.zh_CN.dox, docs/log/dlogmanager.zh_CN.dox
Correct typo and unsuitable description.
Log: correct unsuitable description
=> docs: correct unsuitable description

docs/log/index.zh_CN.md, examples/dlog-example/main.cpp
=> docs: update log index doc

README.md, README.zh_CN.md
=> docs: update readme

archlinux/PKGBUILD
=> chore: update PKGBUILD

docs/dci/ddcifile.zh_CN.dox, docs/global/dconfigfile.zh_CN.dox, docs/global/ddesktopentry.zh_CN.dox, docs/global/dsysinfo.zh_CN.dox, docs/log/Logger.zh_CN.dox, docs/log/RollingFileAppender.zh_CN.dox, docs/util/ddisksizeformatter.zh_CN.dox, docs/util/dtimeunitformatter.zh_CN.dox
=> docs: update enum docs

src/CMakeLists.txt
cmake target private link Qt::CorePrivate
Log: cmake link
=> chore: private link QtCorePrivate

misc/DtkCoreConfig.cmake.in, misc/dtkcore.pc.in, misc/qt_lib_dtkcore.pri.in, src/log/LogManager.cpp
add QT_MESSAGELOGCONTEXT dfinetions by default
log file function line by default
Log: log
Change-Id: I119eb2ffe4ac3d372fba874b99b9fc75131c0d6e
=> chore: log file function and line by default

src/util/dpinyin.cpp
Adapt to qt5
Log: none
Change-Id: I71280483e12d137a7b8710c8617cea6303ad4909
=> fix: Compiling error in qt5

CMakeLists.txt, debian/changelog
Release 5.6.6.
Log: update changelog to 5.6.6
=> chore: update changlog

src/util/dpinyin.cpp
=> fix: fix compile error when using qt6

src/filesystem/dstandardpaths.cpp
Using homePath(uid) to implement homePath().
=> refactor: Removing the same code for homePath

tests/CMakeLists.txt, tests/testso/CMakeLists.txt
=> fix: fix bug of unit test under clang

docs/MainPage.zh_CN.md
- fix typo "camke"
- fix case issue "cmake"
Log: 修复MainPage打字错误：camke。以及cmake大小写错误。
=> docs: fix MainPage typo

src/dsysinfo.cpp
=> chore: support XDG_SESSION_DESKTOP set to DDE

src/log/LogManager.cpp
The log file will not be generated even though we call registerFileAppender when $HOME is empty, it is the default for Qt, But we can fallback it to get the home directory from its user. e.g. for dde-dconfig-daemon, it may be called by a specific user with a home directory but $HOME unset.
=> fix: No log file

examples/dlog-example/main.cpp, include/log/AbstractStringAppender.h, src/log/AbstractStringAppender.cpp, src/log/ConsoleAppender.cpp
Log: add color to ConsoleAppender
=> feat: add color to ConsoleAppender

include/util/dvtablehook.h, src/util/dvtablehook.cpp
https://github.com/linuxdeepin/qt5platform-plugins/commit/623ce74a8ce2dc81e6efad0d271db64736e3b651
Log: 同步qt5platform-plugins
=> fix: sync with qt5platform-plugins

src/log/ConsoleAppender.cpp
Log: use isatty func to check if is stderr is redirected
=> fix: color is in file if is redirect

.reuse/dep5, docs/global/dlicenseinfo.zh_CN.dox, include/DtkCore/DLicenseInfo, include/global/dlicenseinfo.h, src/dlicenseinfo.cpp, src/glob.cmake, tests/data.qrc, tests/data/LGPLv3.txt, tests/data/example-license.json, tests/ut_dutil.cpp
1. add dlicenseinfo interface
2. add dlicenseinfo unit test
3. add dlicenseinfo document
Log: add license information feature
=> feat: add license infomation feature

src/DLicenseInfo, src/dlicenseinfo.cpp, src/dlicenseinfo.h, src/src.pro, tests/data.qrc, tests/data/LGPLv3.txt, tests/data/example-license.json, tests/tests.pro, tests/ut_dutil.cpp
add license feature
Log: add license feature
=> feat: add license feature

docs/global/dconfigfile.zh_CN.dox, include/global/dconfigfile.h, src/dconfigfile.cpp
Export metadir's search path for users.
Issue: https://github.com/linuxdeepin/dtk/issues/10
=> feat: DConfig exports metadir's implementation

src/util/ddbusinterface.cpp, tests/CMakeLists.txt, tests/fakedbus/fakedbusservice.cpp, tests/fakedbus/fakedbusservice.h, tests/ut_ddbusinterface.cpp
Log: fix cannot get the right type
resolve: https://github.com/linuxdeepin/developer-center/issues/4501
=> fix(dccinterface): fix cannot get the right type

src/dsysinfo.cpp, tests/main.cpp, tests/ut_dfilewatchermanager.cpp, tests/ut_dutil.cpp
=> fix(ut): failed ut

src/util/ddbusinterface.cpp
QVariant constructor && QDBusMetaType::demarshall
=> fix(build): build faild on Qt6

include/global/dtkcore_global.h
=> fix: fix build failed due to gcc compiler bug

src/util/dtextencoding.cpp
Delete never be ececuted code, use new-style cast,
avoid "disable expansion of recursive macro".
Log: fix DTextEncoding warnings.
=> fix DTextEncoding warnings.

docs/util/dthreadutils.zh_CN.dox, include/util/dthreadutils.h, src/CMakeLists.txt, src/util/dthreadutils.cpp, src/util/util.cmake, tests/CMakeLists.txt, tests/main.cpp, tests/ut_dthreadutils.cpp, tests/ut_dutil.h
=> feat: add DThreadUtils class

src/CMakeLists.txt
=> fix: move Qt CorePrivate to target private link

include/log/JournalAppender.h
=> chore: function need to be marked as override

.gitignore
log: 在.gitignore文件中添加忽略文件规则
Task: https://github.com/linuxdeepin/dtk/issues/99#issue-1785401780
=> Ignore Doxygen theme files #99

src/util/ddbusinterface.cpp
Log:
resolve: https://github.com/linuxdeepin/developer-center/issues/4872
=> fix: updateProp cannot convert to property type

include/filesystem/dstandardpaths.h, src/filesystem/dstandardpaths.cpp
Log:
A typo , maybe need to remove in dtk6
=> fix: typo in xdg

docs/filesystem/dcapfile.zh_CN.dox, docs/global/dsysinfo.zh_CN.dox, docs/log/Logger.zh_CN.dox
解决docs部分警报
Issue: https://github.com/linuxdeepin/dtk/issues/96
=> chore: reduce compilation warnings

src/filesystem/dcapmanager.cpp
=> chore(dcapmanager): RuntimeTime -> RuntimeDir

docs/util/ddbussender.zh_CN.dox, include/util/ddbussender.h, src/util/ddbussender.cpp
=> feat: add systembus send support

include/global/dlicenseinfo.h, src/util/ddbusextendedabstractinterface.cpp
-    fix: internalPropSet nerver emit propertyChanged
-   chore: should include QVector headers
=> Fix signal not emit &&  include QVector headers

src/dsysinfo.cpp
- add test file path support
- fix ensureDeepinInfo may break loop too ealy
=> chore: dsysinfo tweak

examples/dlog-example/CMakeLists.txt, examples/dlog-example/main.cpp
=> chore: example tweak

src/log/FileAppender.cpp, tests/ut_logger.cpp
log level not set, spdlog default is Info
fix FileAppender ut failed
=> fix: FileAppender log level not set

src/CMakeLists.txt, tests/CMakeLists.txt, tests/test-recoverage.sh
- fix  log level not set（spdlog default is Info），fix FileAppender ut failed
- use linked dtkcore target instead of source code
- test-revoverage.sh tweak
- setup_code_coverage && check_and_add_definitions functions(will move to  dtkcommon
=> Ut build without src

src/CMakeLists.txt, tests/CMakeLists.txt
- use DtkBuildHelper functions
- tests/CMakeLists.txt tweak
=> chore: tweak CMakeLists

examples/dlog-example/main.cpp, include/log/LogManager.h, src/log/LogManager.cpp
=> chore: support Qt 6.4 build

docs/CMakeLists.txt
find qhelpgenerator from CMake Target property
=> chore: qch docs tweak

debian/control
=> chore: add DtkBuildHelper depends

src/log/ConsoleAppender.cpp
=> chore: console with color at tty

.github/workflows/call-synchronize-to-dtk6.yml, .reuse/dep5, .syncexclude, debian/control
Add synchronization workflow which will create a pull request in
linuxdeepin/dtk6core each time there is a pull request opened in
this repo. Add .syncexclude file to exclude some files that should
not be synchronized.
Log: add synchronization workflow
=> feat: add synchronization workflow

docs/global/dconfig.zh_CN.dox, include/global/dconfig.h, src/dbus/org.desktopspec.ConfigManager.Manager.xml, src/dconfig.cpp, src/dconfigfile.cpp, tests/ut_dconfig.cpp
Add isDefaultValue function.
Issue: https://github.com/linuxdeepin/dtk/issues/3
=> Dconfig isdefaultvalue

tools/deepin-os-release/main.cpp
show help instead of show nothing
=> chore(tools): show help if argc < 2

cmake/DtkTools/DtkSettingsToolsMacros.cmake
=> chore: correct typos in DtkSettingsToolsMacros.cmake

docs/util/dutil.zh_CN.dox, include/util/dutil.h
1. get desktop(application)Id from absolute path.
2. get absolute path from desktop(application)Id.
3. escape string to special format which is dbus required.
4. unescape dbus object path
=> feat: add utils function

src/dsgapplication.cpp
- Get appid from dde-application-manager
Also available in the linglong box due to using pidfd
=> chore: Implement DSGApplication::getId

src/log/RollingFileAppender.cpp
=> fix: log files limit not work

LICENSES/BSD-3-Clause.txt, cmake/DtkTools/DtkDBusMacros.cmake, cmake/DtkTools/DtkSettingsToolsMacros.cmake, cmake/DtkTools/DtkToolsConfig.cmake.in, dtkcore.cmake
=> chore: add dtk dbus maro like qt

src/dtkcore_global.cpp
remove unused global functions
=> chore: remove unused code

docs/dci/index.zh_CN.md
=> chore: fix docs typo

tools/qdbusxml2cpp/qdbusxml2cpp.cpp
=> fix(qdbusxml2cpp): support qt 6.7

src/log/LogManager.cpp
fallback to default dsgconfig value
=> chore: fallback to dsgconfig value

include/global/dsysinfo.h
=> feat: 增加智能终端设备类型

src/util/ddbusinterface.cpp
Fix the issue of no signal when DDBusInterface object properties change
=> fix: DDBusInterface signal loss

archlinux/PKGBUILD, debian/rules, dtkcore.cmake, src/log/LogManager.cpp, tests/CMakeLists.txt
BUILD_WITH_SYSTEMD not defined
=> fix(dlog): JournalAppender not work
